//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerTags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerTags.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Custom.
        /// </summary>
        public static string Loc_AllCustomTags {
            get {
                return ResourceManager.GetString("Loc_AllCustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Roles.
        /// </summary>
        public static string Loc_AllRoleTagss {
            get {
                return ResourceManager.GetString("Loc_AllRoleTagss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Loc_AllTags {
            get {
                return ResourceManager.GetString("Loc_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Loc_CustomTags {
            get {
                return ResourceManager.GetString("Loc_CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game object names to apply to.
        /// </summary>
        public static string Loc_GameObjectNamesToApplyTo {
            get {
                return ResourceManager.GetString("Loc_GameObjectNamesToApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of game object names to always apply tags to, separated by commas or semi-colons. E.g. &quot;Cloud Strife, Tifa Lockhart&quot;..
        /// </summary>
        public static string Loc_GameObjectNamesToApplyTo_Description {
            get {
                return ResourceManager.GetString("Loc_GameObjectNamesToApplyTo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Loc_Icon {
            get {
                return ResourceManager.GetString("Loc_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon that will be displayed in the tag..
        /// </summary>
        public static string Loc_Icon_Description {
            get {
                return ResourceManager.GetString("Loc_Icon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the value of this override..
        /// </summary>
        public static string Loc_IsEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_IsEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon visible in chat.
        /// </summary>
        public static string Loc_IsIconVisibleInChatOption {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInChatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the icon is visible in the tag in chat..
        /// </summary>
        public static string Loc_IsIconVisibleInChatOption_Description {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInChatOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon visible in nameplates.
        /// </summary>
        public static string Loc_IsIconVisibleInNameplateOption {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInNameplateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the icon is visible in the tag in nameplates..
        /// </summary>
        public static string Loc_IsIconVisibleInNameplateOption_Description {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInNameplateOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly generate player names.
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use tags to replace every player&apos;s name with a randomly generated one. Helpful for preserving anonymity when taking screenshots..
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text italic.
        /// </summary>
        public static string Loc_IsTextItalicOption {
            get {
                return ResourceManager.GetString("Loc_IsTextItalicOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text in the tag is italic..
        /// </summary>
        public static string Loc_IsTextItalicOption_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextItalicOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text visible in chat.
        /// </summary>
        public static string Loc_IsTextVisibleInChatOption {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInChatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text is visible in the tag in chat..
        /// </summary>
        public static string Loc_IsTextVisibleInChatOption_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInChatOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text visible in nameplates.
        /// </summary>
        public static string Loc_IsTextVisibleInNameplateOption {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInNameplateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text is visible in the tag in nameplates..
        /// </summary>
        public static string Loc_IsTextVisibleInNameplateOption_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInNameplateOption_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free company visibility.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will only be visible when the character is in a free company..
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never visible.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will never be visible..
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title position.
        /// </summary>
        public static string Loc_NameplateTitlePosition {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always above name.
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysAboveName {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysAboveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned above the name..
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysAboveName_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysAboveName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always below name.
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysBelowName {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysBelowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned below the name..
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysBelowName_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysBelowName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateTitlePosition_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will be positioned depending on the title..
        /// </summary>
        public static string Loc_NameplateTitlePosition_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title visibility.
        /// </summary>
        public static string Loc_NameplateTitleVisibility {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always visible.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Always {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be visible, even when the character does not have a title..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Always_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Always_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when the character has a title..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never visible.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will never visible..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible when it has tags.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_WhenHasTags {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_WhenHasTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when it has tags..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_WhenHasTags_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_WhenHasTags_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string Loc_Role_DPS {
            get {
                return ResourceManager.GetString("Loc_Role_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        public static string Loc_Role_Healer {
            get {
                return ResourceManager.GetString("Loc_Role_Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land/Hand.
        /// </summary>
        public static string Loc_Role_LandHand {
            get {
                return ResourceManager.GetString("Loc_Role_LandHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Loc_Role_Tank {
            get {
                return ResourceManager.GetString("Loc_Role_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom tag.
        /// </summary>
        public static string Loc_Static_AddCustomTag {
            get {
                return ResourceManager.GetString("Loc_Static_AddCustomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an override..
        /// </summary>
        public static string Loc_Static_AddPropertyOverride_Description {
            get {
                return ResourceManager.GetString("Loc_Static_AddPropertyOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Loc_Static_Development {
            get {
                return ResourceManager.GetString("Loc_Static_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplates.
        /// </summary>
        public static string Loc_Static_Nameplates {
            get {
                return ResourceManager.GetString("Loc_Static_Nameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Tags.
        /// </summary>
        public static string Loc_Static_PluginName {
            get {
                return ResourceManager.GetString("Loc_Static_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this custom tag.
        /// </summary>
        public static string Loc_Static_RemoveCustomTag {
            get {
                return ResourceManager.GetString("Loc_Static_RemoveCustomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this override. The value will be inherited..
        /// </summary>
        public static string Loc_Static_RemovePropertyOverride_Description {
            get {
                return ResourceManager.GetString("Loc_Static_RemovePropertyOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Loc_Static_Tags {
            get {
                return ResourceManager.GetString("Loc_Static_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin can modify nameplates. When combined with other plugins that modify nameplates, you are likely to see unexpected behavior..
        /// </summary>
        public static string Loc_Static_WarningMessage {
            get {
                return ResourceManager.GetString("Loc_Static_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Loc_TagPosition_After {
            get {
                return ResourceManager.GetString("Loc_TagPosition_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the tag after the target element..
        /// </summary>
        public static string Loc_TagPosition_After_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_After_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Loc_TagPosition_Before {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the tag before the target element..
        /// </summary>
        public static string Loc_TagPosition_Before_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Before_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Loc_TagPosition_Replace {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the target element with the tag..
        /// </summary>
        public static string Loc_TagPosition_Replace_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Replace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag position in chat.
        /// </summary>
        public static string Loc_TagPositionInChat {
            get {
                return ResourceManager.GetString("Loc_TagPositionInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the tag should be positioned in chat..
        /// </summary>
        public static string Loc_TagPositionInChat_Description {
            get {
                return ResourceManager.GetString("Loc_TagPositionInChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag position in chat.
        /// </summary>
        public static string Loc_TagPositionInNameplates {
            get {
                return ResourceManager.GetString("Loc_TagPositionInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the tag should be positioned in nameplates..
        /// </summary>
        public static string Loc_TagPositionInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_TagPositionInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag target in chat.
        /// </summary>
        public static string Loc_TagTargetInNameplates {
            get {
                return ResourceManager.GetString("Loc_TagTargetInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element that the tag should target in nameplates..
        /// </summary>
        public static string Loc_TagTargetInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_TagTargetInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Loc_Text {
            get {
                return ResourceManager.GetString("Loc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text that will be displayed in the tag..
        /// </summary>
        public static string Loc_Text_Description {
            get {
                return ResourceManager.GetString("Loc_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string Loc_TextColorOption {
            get {
                return ResourceManager.GetString("Loc_TextColorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the text in the tag..
        /// </summary>
        public static string Loc_TextColorOption_Description {
            get {
                return ResourceManager.GetString("Loc_TextColorOption_Description", resourceCulture);
            }
        }
    }
}
