//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerTags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerTags.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity properties.
        /// </summary>
        public static string Loc_ActivityCategory {
            get {
                return ResourceManager.GetString("Loc_ActivityCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Custom.
        /// </summary>
        public static string Loc_AllCustomTags {
            get {
                return ResourceManager.GetString("Loc_AllCustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Roles.
        /// </summary>
        public static string Loc_AllRoleTags {
            get {
                return ResourceManager.GetString("Loc_AllRoleTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Loc_AllTags {
            get {
                return ResourceManager.GetString("Loc_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Loc_CustomTags {
            get {
                return ResourceManager.GetString("Loc_CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to players.
        /// </summary>
        public static string Loc_GameObjectNamesToApplyTo {
            get {
                return ResourceManager.GetString("Loc_GameObjectNamesToApplyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of players to add tags to, separated by commas or semi-colons. E.g. &quot;Cloud Strife, Tifa Lockhart&quot;..
        /// </summary>
        public static string Loc_GameObjectNamesToApplyTo_Description {
            get {
                return ResourceManager.GetString("Loc_GameObjectNamesToApplyTo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General properties.
        /// </summary>
        public static string Loc_GeneralCategory {
            get {
                return ResourceManager.GetString("Loc_GeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Loc_Icon {
            get {
                return ResourceManager.GetString("Loc_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon that will be displayed..
        /// </summary>
        public static string Loc_Icon_Description {
            get {
                return ResourceManager.GetString("Loc_Icon_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon properties.
        /// </summary>
        public static string Loc_IconCategory {
            get {
                return ResourceManager.GetString("Loc_IconCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu integration.
        /// </summary>
        public static string Loc_IsCustomTagsContextMenuEnabled {
            get {
                return ResourceManager.GetString("Loc_IsCustomTagsContextMenuEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options will be available in context menus for adding and removing custom tags from players..
        /// </summary>
        public static string Loc_IsCustomTagsContextMenuEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_IsCustomTagsContextMenuEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Loc_IsEnabled {
            get {
                return ResourceManager.GetString("Loc_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the value of this override..
        /// </summary>
        public static string Loc_IsEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_IsEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        public static string Loc_IsExpanded {
            get {
                return ResourceManager.GetString("Loc_IsExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in chat.
        /// </summary>
        public static string Loc_IsIconVisibleInChat {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the icon will be shown in chat..
        /// </summary>
        public static string Loc_IsIconVisibleInChat_Description {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in nameplates.
        /// </summary>
        public static string Loc_IsIconVisibleInNameplates {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the icon will be shown in nameplates..
        /// </summary>
        public static string Loc_IsIconVisibleInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_IsIconVisibleInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly generate player names.
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace every player&apos;s name with a randomly generated one..
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show alliance members.
        /// </summary>
        public static string Loc_IsPlayersTabAllianceVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabAllianceVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show alliance members in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabAllianceVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabAllianceVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show enemies.
        /// </summary>
        public static string Loc_IsPlayersTabEnemiesVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabEnemiesVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show enemies in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabEnemiesVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabEnemiesVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show friends.
        /// </summary>
        public static string Loc_IsPlayersTabFriendsVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabFriendsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show friends in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabFriendsVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabFriendsVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by proximity.
        /// </summary>
        public static string Loc_IsPlayersTabOrderedByProximity {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabOrderedByProximity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players that are closer to you will be ordered towards the top..
        /// </summary>
        public static string Loc_IsPlayersTabOrderedByProximity_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabOrderedByProximity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show others.
        /// </summary>
        public static string Loc_IsPlayersTabOthersVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabOthersVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show others in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabOthersVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabOthersVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show party members.
        /// </summary>
        public static string Loc_IsPlayersTabPartyVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabPartyVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show party members in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabPartyVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabPartyVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show self.
        /// </summary>
        public static string Loc_IsPlayersTabSelfVisible {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabSelfVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show yourself in the players list..
        /// </summary>
        public static string Loc_IsPlayersTabSelfVisible_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayersTabSelfVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Loc_IsSelected {
            get {
                return ResourceManager.GetString("Loc_IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show inherited properties.
        /// </summary>
        public static string Loc_IsShowInheritedPropertiesEnabled {
            get {
                return ResourceManager.GetString("Loc_IsShowInheritedPropertiesEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties inherited from parent nodes will be shown in the editor..
        /// </summary>
        public static string Loc_IsShowInheritedPropertiesEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_IsShowInheritedPropertiesEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply color to chat name.
        /// </summary>
        public static string Loc_IsTextColorAppliedToChatName {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToChatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the color will be applied to the name in chat..
        /// </summary>
        public static string Loc_IsTextColorAppliedToChatName_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToChatName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply color to nameplate free company.
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateFreeCompany {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateFreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the color will be applied to the free company in nameplates..
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateFreeCompany_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateFreeCompany_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply color to nameplate name.
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateName {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the color will be applied to the name in nameplates..
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateName_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply color to nameplate title.
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateTitle {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the color will be applied to title in nameplates..
        /// </summary>
        public static string Loc_IsTextColorAppliedToNameplateTitle_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextColorAppliedToNameplateTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string Loc_IsTextItalic {
            get {
                return ResourceManager.GetString("Loc_IsTextItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text will be italic..
        /// </summary>
        public static string Loc_IsTextItalic_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextItalic_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in chat.
        /// </summary>
        public static string Loc_IsTextVisibleInChat {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text will be shown in chat..
        /// </summary>
        public static string Loc_IsTextVisibleInChat_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in nameplates.
        /// </summary>
        public static string Loc_IsTextVisibleInNameplates {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the text will be shown in nameplates..
        /// </summary>
        public static string Loc_IsTextVisibleInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_IsTextVisibleInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for alliance members.
        /// </summary>
        public static string Loc_IsVisibleForAlliancePlayers {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForAlliancePlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for alliance members who are not in the current party..
        /// </summary>
        public static string Loc_IsVisibleForAlliancePlayers_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForAlliancePlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for enemies.
        /// </summary>
        public static string Loc_IsVisibleForEnemyPlayers {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForEnemyPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for enemies in pvp..
        /// </summary>
        public static string Loc_IsVisibleForEnemyPlayers_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForEnemyPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for friends.
        /// </summary>
        public static string Loc_IsVisibleForFriendPlayers {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForFriendPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for friends..
        /// </summary>
        public static string Loc_IsVisibleForFriendPlayers_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForFriendPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for others.
        /// </summary>
        public static string Loc_IsVisibleForOtherPlayers {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForOtherPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for players in other circumstances for which there is no specific option..
        /// </summary>
        public static string Loc_IsVisibleForOtherPlayers_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForOtherPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for party members.
        /// </summary>
        public static string Loc_IsVisibleForPartyPlayers {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForPartyPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for party members..
        /// </summary>
        public static string Loc_IsVisibleForPartyPlayers_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForPartyPlayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show for self.
        /// </summary>
        public static string Loc_IsVisibleForSelf {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible for the local player..
        /// </summary>
        public static string Loc_IsVisibleForSelf_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleForSelf_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show elsewhere.
        /// </summary>
        public static string Loc_IsVisibleInOverworld {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInOverworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible in other circumstances for which there is no specific option..
        /// </summary>
        public static string Loc_IsVisibleInOverworld_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInOverworld_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in pve duties.
        /// </summary>
        public static string Loc_IsVisibleInPveDuties {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInPveDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible in pve duties..
        /// </summary>
        public static string Loc_IsVisibleInPveDuties_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInPveDuties_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in pvp duties.
        /// </summary>
        public static string Loc_IsVisibleInPvpDuties {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInPvpDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the tag should be visible in pvp duties..
        /// </summary>
        public static string Loc_IsVisibleInPvpDuties_Description {
            get {
                return ResourceManager.GetString("Loc_IsVisibleInPvpDuties_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free company.
        /// </summary>
        public static string Loc_NameplateElement_FreeCompany {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company element on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_FreeCompany_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_FreeCompany_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Loc_NameplateElement_Name {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name element on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_Name_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Loc_NameplateElement_Title {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title element on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_Title_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free company visibility.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will only be visible when the character is in a free company..
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never visible.
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will never be visible..
        /// </summary>
        public static string Loc_NameplateFreeCompanyVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateFreeCompanyVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title position.
        /// </summary>
        public static string Loc_NameplateTitlePosition {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always above name.
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysAboveName {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysAboveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned above the name..
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysAboveName_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysAboveName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always below name.
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysBelowName {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysBelowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned below the name..
        /// </summary>
        public static string Loc_NameplateTitlePosition_AlwaysBelowName_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_AlwaysBelowName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateTitlePosition_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will be positioned depending on the title..
        /// </summary>
        public static string Loc_NameplateTitlePosition_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitlePosition_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title visibility.
        /// </summary>
        public static string Loc_NameplateTitleVisibility {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always visible.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Always {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be visible, even when the character does not have a title..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Always_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Always_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when the character has a title..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never visible.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will never visible..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only visible when it has tags.
        /// </summary>
        public static string Loc_NameplateTitleVisibility_WhenHasTags {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_WhenHasTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when it has tags..
        /// </summary>
        public static string Loc_NameplateTitleVisibility_WhenHasTags_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateTitleVisibility_WhenHasTags_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player properties.
        /// </summary>
        public static string Loc_PlayerCategory {
            get {
                return ResourceManager.GetString("Loc_PlayerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position properties.
        /// </summary>
        public static string Loc_PositionCategory {
            get {
                return ResourceManager.GetString("Loc_PositionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string Loc_Role_DPS {
            get {
                return ResourceManager.GetString("Loc_Role_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        public static string Loc_Role_Healer {
            get {
                return ResourceManager.GetString("Loc_Role_Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land/Hand.
        /// </summary>
        public static string Loc_Role_LandHand {
            get {
                return ResourceManager.GetString("Loc_Role_LandHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Loc_Role_Tank {
            get {
                return ResourceManager.GetString("Loc_Role_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a custom tag..
        /// </summary>
        public static string Loc_Static_AddCustomTag_Description {
            get {
                return ResourceManager.GetString("Loc_Static_AddCustomTag_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a property override..
        /// </summary>
        public static string Loc_Static_AddPropertyOverride_Description {
            get {
                return ResourceManager.GetString("Loc_Static_AddPropertyOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string Loc_Static_ContextMenu_AddTag {
            get {
                return ResourceManager.GetString("Loc_Static_ContextMenu_AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        public static string Loc_Static_ContextMenu_RemoveTag {
            get {
                return ResourceManager.GetString("Loc_Static_ContextMenu_RemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Loc_Static_Development {
            get {
                return ResourceManager.GetString("Loc_Static_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &apos;{0}&apos; to {1}..
        /// </summary>
        public static string Loc_Static_Format_AddTagToPlayer {
            get {
                return ResourceManager.GetString("Loc_Static_Format_AddTagToPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Loc_Static_General {
            get {
                return ResourceManager.GetString("Loc_Static_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Inherited&gt;.
        /// </summary>
        public static string Loc_Static_Inherited {
            get {
                return ResourceManager.GetString("Loc_Static_Inherited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplates.
        /// </summary>
        public static string Loc_Static_Nameplates {
            get {
                return ResourceManager.GetString("Loc_Static_Nameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag.
        /// </summary>
        public static string Loc_Static_NewTag {
            get {
                return ResourceManager.GetString("Loc_Static_NewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string Loc_Static_PlayerName {
            get {
                return ResourceManager.GetString("Loc_Static_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Tags.
        /// </summary>
        public static string Loc_Static_PluginName {
            get {
                return ResourceManager.GetString("Loc_Static_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Tag.
        /// </summary>
        public static string Loc_Static_QuickTag {
            get {
                return ResourceManager.GetString("Loc_Static_QuickTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this custom tag..
        /// </summary>
        public static string Loc_Static_RemoveCustomTag_Description {
            get {
                return ResourceManager.GetString("Loc_Static_RemoveCustomTag_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this property override. The value will be inherited from the parent tag..
        /// </summary>
        public static string Loc_Static_RemovePropertyOverride_Description {
            get {
                return ResourceManager.GetString("Loc_Static_RemovePropertyOverride_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged Players.
        /// </summary>
        public static string Loc_Static_TaggedPlayers {
            get {
                return ResourceManager.GetString("Loc_Static_TaggedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Loc_Static_Tags {
            get {
                return ResourceManager.GetString("Loc_Static_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This plugin can modify nameplates. When combined with other plugins that modify nameplates, you are likely to see unexpected behavior..
        /// </summary>
        public static string Loc_Static_WarningMessage {
            get {
                return ResourceManager.GetString("Loc_Static_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Loc_TagPosition_After {
            get {
                return ResourceManager.GetString("Loc_TagPosition_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the tag after the target element..
        /// </summary>
        public static string Loc_TagPosition_After_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_After_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Loc_TagPosition_Before {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the tag before the target element..
        /// </summary>
        public static string Loc_TagPosition_Before_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Before_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Loc_TagPosition_Replace {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace the target element with the tag..
        /// </summary>
        public static string Loc_TagPosition_Replace_Description {
            get {
                return ResourceManager.GetString("Loc_TagPosition_Replace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in chat.
        /// </summary>
        public static string Loc_TagPositionInChat {
            get {
                return ResourceManager.GetString("Loc_TagPositionInChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the tag will be positioned in chat..
        /// </summary>
        public static string Loc_TagPositionInChat_Description {
            get {
                return ResourceManager.GetString("Loc_TagPositionInChat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in nameplates.
        /// </summary>
        public static string Loc_TagPositionInNameplates {
            get {
                return ResourceManager.GetString("Loc_TagPositionInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where the tag will be positioned in nameplates..
        /// </summary>
        public static string Loc_TagPositionInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_TagPositionInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target in nameplates.
        /// </summary>
        public static string Loc_TagTargetInNameplates {
            get {
                return ResourceManager.GetString("Loc_TagTargetInNameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element that the tag should target in nameplates..
        /// </summary>
        public static string Loc_TagTargetInNameplates_Description {
            get {
                return ResourceManager.GetString("Loc_TagTargetInNameplates_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Loc_Text {
            get {
                return ResourceManager.GetString("Loc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text that will be displayed..
        /// </summary>
        public static string Loc_Text_Description {
            get {
                return ResourceManager.GetString("Loc_Text_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text properties.
        /// </summary>
        public static string Loc_TextCategory {
            get {
                return ResourceManager.GetString("Loc_TextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Loc_TextColor {
            get {
                return ResourceManager.GetString("Loc_TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the text..
        /// </summary>
        public static string Loc_TextColor_Description {
            get {
                return ResourceManager.GetString("Loc_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glow color.
        /// </summary>
        public static string Loc_TextGlowColor {
            get {
                return ResourceManager.GetString("Loc_TextGlowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The glow color of the text..
        /// </summary>
        public static string Loc_TextGlowColor_Description {
            get {
                return ResourceManager.GetString("Loc_TextGlowColor_Description", resourceCulture);
            }
        }
    }
}
