//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayerTags.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayerTags.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Loc_CustomColorConfig_IsEnabled {
            get {
                return ResourceManager.GetString("Loc_CustomColorConfig_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable a custom color..
        /// </summary>
        public static string Loc_CustomColorConfig_IsEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_CustomColorConfig_IsEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to game object names.
        /// </summary>
        public static string Loc_CustomTagConfig_FormattedGameObjectNames {
            get {
                return ResourceManager.GetString("Loc_CustomTagConfig_FormattedGameObjectNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of game object names to apply the tag to, separated by commas. E.g. &quot;Cloud Strife, Tifa Lockhart&quot;.
        /// </summary>
        public static string Loc_CustomTagConfig_FormattedGameObjectNames_Description {
            get {
                return ResourceManager.GetString("Loc_CustomTagConfig_FormattedGameObjectNames_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Loc_CustomTagConfig_Name {
            get {
                return ResourceManager.GetString("Loc_CustomTagConfig_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the tag to display..
        /// </summary>
        public static string Loc_CustomTagConfig_Name_Description {
            get {
                return ResourceManager.GetString("Loc_CustomTagConfig_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free company visibility.
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will only be visible when the character is in a free company..
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visibility of the free company on nameplates..
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility_Description {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never visible.
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates will never be visible..
        /// </summary>
        public static string Loc_FreeCompanyNameplateVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_FreeCompanyNameplateVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomly generate player names.
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use tags to replace every player&apos;s name with a randomly generated one. Helpful for preserving anonymity when taking screenshots..
        /// </summary>
        public static string Loc_IsPlayerNameRandomlyGenerated_Description {
            get {
                return ResourceManager.GetString("Loc_IsPlayerNameRandomlyGenerated_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data element.
        /// </summary>
        public static string Loc_NameplateElement {
            get {
                return ResourceManager.GetString("Loc_NameplateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data element on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free company.
        /// </summary>
        public static string Loc_NameplateElement_FreeCompany {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_FreeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The free company on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_FreeCompany_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_FreeCompany_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Loc_NameplateElement_Name {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_Name_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Loc_NameplateElement_Title {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates..
        /// </summary>
        public static string Loc_NameplateElement_Title_Description {
            get {
                return ResourceManager.GetString("Loc_NameplateElement_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Loc_Role {
            get {
                return ResourceManager.GetString("Loc_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A character role..
        /// </summary>
        public static string Loc_Role_Description {
            get {
                return ResourceManager.GetString("Loc_Role_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPS.
        /// </summary>
        public static string Loc_Role_DPS {
            get {
                return ResourceManager.GetString("Loc_Role_DPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DPS role..
        /// </summary>
        public static string Loc_Role_DPS_Description {
            get {
                return ResourceManager.GetString("Loc_Role_DPS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Healer.
        /// </summary>
        public static string Loc_Role_Healer {
            get {
                return ResourceManager.GetString("Loc_Role_Healer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The healer role..
        /// </summary>
        public static string Loc_Role_Healer_Description {
            get {
                return ResourceManager.GetString("Loc_Role_Healer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land/Hand.
        /// </summary>
        public static string Loc_Role_LandHand {
            get {
                return ResourceManager.GetString("Loc_Role_LandHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The land/hand role..
        /// </summary>
        public static string Loc_Role_LandHand_Description {
            get {
                return ResourceManager.GetString("Loc_Role_LandHand_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank.
        /// </summary>
        public static string Loc_Role_Tank {
            get {
                return ResourceManager.GetString("Loc_Role_Tank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tank role..
        /// </summary>
        public static string Loc_Role_Tank_Description {
            get {
                return ResourceManager.GetString("Loc_Role_Tank_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Loc_RoleOverrideConfig_IsEnabled {
            get {
                return ResourceManager.GetString("Loc_RoleOverrideConfig_IsEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the tag for this role..
        /// </summary>
        public static string Loc_RoleOverrideConfig_IsEnabled_Description {
            get {
                return ResourceManager.GetString("Loc_RoleOverrideConfig_IsEnabled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Loc_RoleOverrideConfig_Name {
            get {
                return ResourceManager.GetString("Loc_RoleOverrideConfig_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name to use for this role when the format is set to use role names..
        /// </summary>
        public static string Loc_RoleOverrideConfig_Name_Description {
            get {
                return ResourceManager.GetString("Loc_RoleOverrideConfig_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag format.
        /// </summary>
        public static string Loc_RoleTagFormat {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviated job name.
        /// </summary>
        public static string Loc_RoleTagFormat_AbbreviatedJobName {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_AbbreviatedJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will appear as an abbreviated job name, e.g. SAM, WHM, GNB..
        /// </summary>
        public static string Loc_RoleTagFormat_AbbreviatedJobName_Description {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_AbbreviatedJobName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format that the role tag should be displayed as..
        /// </summary>
        public static string Loc_RoleTagFormat_Description {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job name.
        /// </summary>
        public static string Loc_RoleTagFormat_JobName {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_JobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will appear as a job name in English, e.g. Samurai, White Mage, Gunbreaker..
        /// </summary>
        public static string Loc_RoleTagFormat_JobName_Description {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_JobName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string Loc_RoleTagFormat_RoleName {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will appear as the configured role name, e.g. DPS, Healer, Tank..
        /// </summary>
        public static string Loc_RoleTagFormat_RoleName_Description {
            get {
                return ResourceManager.GetString("Loc_RoleTagFormat_RoleName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom tag.
        /// </summary>
        public static string Loc_Static_AddCustomTag {
            get {
                return ResourceManager.GetString("Loc_Static_AddCustomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat tag.
        /// </summary>
        public static string Loc_Static_ChatTag {
            get {
                return ResourceManager.GetString("Loc_Static_ChatTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom tags.
        /// </summary>
        public static string Loc_Static_CustomTags {
            get {
                return ResourceManager.GetString("Loc_Static_CustomTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Loc_Static_Development {
            get {
                return ResourceManager.GetString("Loc_Static_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Loc_Static_General {
            get {
                return ResourceManager.GetString("Loc_Static_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Loc_Static_Jobs {
            get {
                return ResourceManager.GetString("Loc_Static_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplates.
        /// </summary>
        public static string Loc_Static_Nameplates {
            get {
                return ResourceManager.GetString("Loc_Static_Nameplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nameplate tag.
        /// </summary>
        public static string Loc_Static_NameplateTag {
            get {
                return ResourceManager.GetString("Loc_Static_NameplateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom tags added..
        /// </summary>
        public static string Loc_Static_NoCustomTagsAdded {
            get {
                return ResourceManager.GetString("Loc_Static_NoCustomTagsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Tags.
        /// </summary>
        public static string Loc_Static_PluginName {
            get {
                return ResourceManager.GetString("Loc_Static_PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove custom tag.
        /// </summary>
        public static string Loc_Static_RemoveCustomTag {
            get {
                return ResourceManager.GetString("Loc_Static_RemoveCustomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role and job tags.
        /// </summary>
        public static string Loc_Static_RoleAndJobTags {
            get {
                return ResourceManager.GetString("Loc_Static_RoleAndJobTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Loc_Static_Roles {
            get {
                return ResourceManager.GetString("Loc_Static_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String position.
        /// </summary>
        public static string Loc_StringPosition {
            get {
                return ResourceManager.GetString("Loc_StringPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Loc_StringPosition_After {
            get {
                return ResourceManager.GetString("Loc_StringPosition_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will be positioned after the data element..
        /// </summary>
        public static string Loc_StringPosition_After_Description {
            get {
                return ResourceManager.GetString("Loc_StringPosition_After_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Loc_StringPosition_Before {
            get {
                return ResourceManager.GetString("Loc_StringPosition_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will be positioned before the data element..
        /// </summary>
        public static string Loc_StringPosition_Before_Description {
            get {
                return ResourceManager.GetString("Loc_StringPosition_Before_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position in a string where tags will be displayed..
        /// </summary>
        public static string Loc_StringPosition_Description {
            get {
                return ResourceManager.GetString("Loc_StringPosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Loc_StringPosition_None {
            get {
                return ResourceManager.GetString("Loc_StringPosition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will not be positioned in the string..
        /// </summary>
        public static string Loc_StringPosition_None_Description {
            get {
                return ResourceManager.GetString("Loc_StringPosition_None_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string Loc_StringPosition_Replace {
            get {
                return ResourceManager.GetString("Loc_StringPosition_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag will replace its data element..
        /// </summary>
        public static string Loc_StringPosition_Replace_Description {
            get {
                return ResourceManager.GetString("Loc_StringPosition_Replace_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title position.
        /// </summary>
        public static string Loc_TitleNameplatePosition {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always above the name.
        /// </summary>
        public static string Loc_TitleNameplatePosition_AlwaysAboveName {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_AlwaysAboveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned above the name..
        /// </summary>
        public static string Loc_TitleNameplatePosition_AlwaysAboveName_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_AlwaysAboveName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always below the name.
        /// </summary>
        public static string Loc_TitleNameplatePosition_AlwaysBelowName {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_AlwaysBelowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be positioned below the name..
        /// </summary>
        public static string Loc_TitleNameplatePosition_AlwaysBelowName_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_AlwaysBelowName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_TitleNameplatePosition_Default {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will be positioned depending on the title..
        /// </summary>
        public static string Loc_TitleNameplatePosition_Default_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position of the title on nameplates..
        /// </summary>
        public static string Loc_TitleNameplatePosition_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplatePosition_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title visibility.
        /// </summary>
        public static string Loc_TitleNameplateVisibility {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Always {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will always be visible, even when the character does not have a title..
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Always_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Always_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Default {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when the character has a title..
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Default_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Default_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The visibility of the title on nameplates..
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Never {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will never visible..
        /// </summary>
        public static string Loc_TitleNameplateVisibility_Never_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_Never_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When it has tags.
        /// </summary>
        public static string Loc_TitleNameplateVisibility_WhenHasTags {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_WhenHasTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title on nameplates will only be visible when it has tags..
        /// </summary>
        public static string Loc_TitleNameplateVisibility_WhenHasTags_Description {
            get {
                return ResourceManager.GetString("Loc_TitleNameplateVisibility_WhenHasTags_Description", resourceCulture);
            }
        }
    }
}
